version: '3.8'

services:
  aws-cli:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID=your-access-key-id
      - AWS_SECRET_ACCESS_KEY=your-secret-access-key
      - AWS_DEFAULT_REGION=your-default-region
    volumes:
      - ./cloudformation:/aws/cloudformation
    command: ./create_ou.sh