services:
  vue-capacitor:
    build:
      target: runtime
      context: .
    ports:
      - "8080:8080"
    command: ["serve", "-s", "dist", "-l", "8080"]

  android-builder:
    build:
      context: .
      target: android-sdk
    volumes:
      - .:/app
    command: ["./build-apk.sh"]

