services:
  web-builder:
    build:
      dockerfile: dockerfiles/web-build.Dockerfile
    volumes:
      - ./app/dist:/app/dist

  web-server:
    build:
      dockerfile: dockerfiles/web-serve.Dockerfile
    ports:
       - "8080:80"

  android-builder:
    build:
      dockerfile: dockerfiles/android-build.Dockerfile
    volumes:
      - ./app/android-build:/app/android-build