services:
  web-autosync:
    build:
      dockerfile: dockerfiles/web-base.Dockerfile
    ports:
       - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app
#    command: "npm run dev -- --port 3000"
    command: "npm run serve -- --port 3000"

  web-builder:
    build:
      dockerfile: dockerfiles/web-base.Dockerfile
    volumes:
      - ./app/dist:/app/dist
    command: "npx vue-cli-service build --target app --modern"

  web-server:
    build:
      dockerfile: dockerfiles/web-serve.Dockerfile
    ports:
       - "8080:80"
    volumes:
      - ./app/dist:/usr/share/nginx/html:ro
      - ./server/nginx.conf:/etc/nginx/nginx.conf

  android-builder:
    build:
      dockerfile: dockerfiles/android-build.Dockerfile
    volumes:
      - ./app/dist-apk:/app/dist-apk